#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lw.Ads
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="3ikar")]
	public partial class AdsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAd(Ad instance);
    partial void UpdateAd(Ad instance);
    partial void DeleteAd(Ad instance);
    partial void InsertAds_AdKeywordRelation(Ads_AdKeywordRelation instance);
    partial void UpdateAds_AdKeywordRelation(Ads_AdKeywordRelation instance);
    partial void DeleteAds_AdKeywordRelation(Ads_AdKeywordRelation instance);
    partial void InsertAds_Keyword(Ads_Keyword instance);
    partial void UpdateAds_Keyword(Ads_Keyword instance);
    partial void DeleteAds_Keyword(Ads_Keyword instance);
    partial void InsertAds_Zone(Ads_Zone instance);
    partial void UpdateAds_Zone(Ads_Zone instance);
    partial void DeleteAds_Zone(Ads_Zone instance);
    #endregion
		
		public AdsDataContext() : 
				base(global::lw.Ads.Properties.Settings.Default._3ikarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ad> Ads
		{
			get
			{
				return this.GetTable<Ad>();
			}
		}
		
		public System.Data.Linq.Table<Ads_AdKeywordRelation> Ads_AdKeywordRelations
		{
			get
			{
				return this.GetTable<Ads_AdKeywordRelation>();
			}
		}
		
		public System.Data.Linq.Table<Ads_Report> Ads_Reports
		{
			get
			{
				return this.GetTable<Ads_Report>();
			}
		}
		
		public System.Data.Linq.Table<AdsView> AdsViews
		{
			get
			{
				return this.GetTable<AdsView>();
			}
		}
		
		public System.Data.Linq.Table<Ads_ReportsView> Ads_ReportsViews
		{
			get
			{
				return this.GetTable<Ads_ReportsView>();
			}
		}
		
		public System.Data.Linq.Table<Ads_Keyword> Ads_Keywords
		{
			get
			{
				return this.GetTable<Ads_Keyword>();
			}
		}
		
		public System.Data.Linq.Table<Ads_Zone> Ads_Zones
		{
			get
			{
				return this.GetTable<Ads_Zone>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ads_CreateAdvertiser")]
		public int Ads_CreateAdvertiser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Advertiser", DbType="NVarChar(256)")] string advertiser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdvertiserId", DbType="Int")] ref System.Nullable<int> advertiserId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), advertiser, advertiserId);
			advertiserId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ads_UpdateImpressions")]
		public int Ads_UpdateImpressions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdId", DbType="Int")] System.Nullable<int> adId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Click", DbType="Bit")] System.Nullable<bool> click)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adId, click);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ads_CreateKeyword")]
		public int Ads_CreateKeyword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keyword", DbType="NVarChar(50)")] string keyword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeywordId", DbType="Int")] ref System.Nullable<int> keywordId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword, keywordId);
			keywordId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdId;
		
		private string _Name;
		
		private System.Nullable<int> _AdvertiserId;
		
		private System.Nullable<short> _Status;
		
		private System.Nullable<int> _ZoneId;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<short> _PaymentType;
		
		private System.Nullable<int> _UnitsPurchased;
		
		private System.Nullable<decimal> _CostPerUnit;
		
		private string _Image;
		
		private string _Description;
		
		private string _HtmlCode;
		
		private string _URL;
		
		private System.Nullable<bool> _NewWindow;
		
		private System.Nullable<short> _Weight;
		
		private System.Nullable<int> _MaxImpressionPerHour;
		
		private System.Nullable<int> _MaxImpressionPerDay;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private EntitySet<Ads_AdKeywordRelation> _Ads_AdKeywordRelations;
		
		private EntityRef<Ads_Zone> _Ads_Zone;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdIdChanging(int value);
    partial void OnAdIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdvertiserIdChanging(System.Nullable<int> value);
    partial void OnAdvertiserIdChanged();
    partial void OnStatusChanging(System.Nullable<short> value);
    partial void OnStatusChanged();
    partial void OnZoneIdChanging(System.Nullable<int> value);
    partial void OnZoneIdChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnPaymentTypeChanging(System.Nullable<short> value);
    partial void OnPaymentTypeChanged();
    partial void OnUnitsPurchasedChanging(System.Nullable<int> value);
    partial void OnUnitsPurchasedChanged();
    partial void OnCostPerUnitChanging(System.Nullable<decimal> value);
    partial void OnCostPerUnitChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnHtmlCodeChanging(string value);
    partial void OnHtmlCodeChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnNewWindowChanging(System.Nullable<bool> value);
    partial void OnNewWindowChanged();
    partial void OnWeightChanging(System.Nullable<short> value);
    partial void OnWeightChanged();
    partial void OnMaxImpressionPerHourChanging(System.Nullable<int> value);
    partial void OnMaxImpressionPerHourChanged();
    partial void OnMaxImpressionPerDayChanging(System.Nullable<int> value);
    partial void OnMaxImpressionPerDayChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    #endregion
		
		public Ad()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this.OnAdIdChanging(value);
					this.SendPropertyChanging();
					this._AdId = value;
					this.SendPropertyChanged("AdId");
					this.OnAdIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> AdvertiserId
		{
			get
			{
				return this._AdvertiserId;
			}
			set
			{
				if ((this._AdvertiserId != value))
				{
					this.OnAdvertiserIdChanging(value);
					this.SendPropertyChanging();
					this._AdvertiserId = value;
					this.SendPropertyChanged("AdvertiserId");
					this.OnAdvertiserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<short> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> ZoneId
		{
			get
			{
				return this._ZoneId;
			}
			set
			{
				if ((this._ZoneId != value))
				{
					if (this._Ads_Zone.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnZoneIdChanging(value);
					this.SendPropertyChanging();
					this._ZoneId = value;
					this.SendPropertyChanged("ZoneId");
					this.OnZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<short> PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this.OnPaymentTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentType = value;
					this.SendPropertyChanged("PaymentType");
					this.OnPaymentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsPurchased", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> UnitsPurchased
		{
			get
			{
				return this._UnitsPurchased;
			}
			set
			{
				if ((this._UnitsPurchased != value))
				{
					this.OnUnitsPurchasedChanging(value);
					this.SendPropertyChanging();
					this._UnitsPurchased = value;
					this.SendPropertyChanged("UnitsPurchased");
					this.OnUnitsPurchasedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostPerUnit", DbType="Money")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<decimal> CostPerUnit
		{
			get
			{
				return this._CostPerUnit;
			}
			set
			{
				if ((this._CostPerUnit != value))
				{
					this.OnCostPerUnitChanging(value);
					this.SendPropertyChanging();
					this._CostPerUnit = value;
					this.SendPropertyChanged("CostPerUnit");
					this.OnCostPerUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HtmlCode", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string HtmlCode
		{
			get
			{
				return this._HtmlCode;
			}
			set
			{
				if ((this._HtmlCode != value))
				{
					this.OnHtmlCodeChanging(value);
					this.SendPropertyChanging();
					this._HtmlCode = value;
					this.SendPropertyChanged("HtmlCode");
					this.OnHtmlCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(512)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWindow", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<bool> NewWindow
		{
			get
			{
				return this._NewWindow;
			}
			set
			{
				if ((this._NewWindow != value))
				{
					this.OnNewWindowChanging(value);
					this.SendPropertyChanging();
					this._NewWindow = value;
					this.SendPropertyChanged("NewWindow");
					this.OnNewWindowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<short> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxImpressionPerHour", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> MaxImpressionPerHour
		{
			get
			{
				return this._MaxImpressionPerHour;
			}
			set
			{
				if ((this._MaxImpressionPerHour != value))
				{
					this.OnMaxImpressionPerHourChanging(value);
					this.SendPropertyChanging();
					this._MaxImpressionPerHour = value;
					this.SendPropertyChanged("MaxImpressionPerHour");
					this.OnMaxImpressionPerHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxImpressionPerDay", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<int> MaxImpressionPerDay
		{
			get
			{
				return this._MaxImpressionPerDay;
			}
			set
			{
				if ((this._MaxImpressionPerDay != value))
				{
					this.OnMaxImpressionPerDayChanging(value);
					this.SendPropertyChanging();
					this._MaxImpressionPerDay = value;
					this.SendPropertyChanged("MaxImpressionPerDay");
					this.OnMaxImpressionPerDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ad_Ads_AdKeywordRelation", Storage="_Ads_AdKeywordRelations", ThisKey="AdId", OtherKey="AdId")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21, EmitDefaultValue=false)]
		public EntitySet<Ads_AdKeywordRelation> Ads_AdKeywordRelations
		{
			get
			{
				if ((this.serializing 
							&& (this._Ads_AdKeywordRelations.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Ads_AdKeywordRelations;
			}
			set
			{
				this._Ads_AdKeywordRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ads_Zone_Ad", Storage="_Ads_Zone", ThisKey="ZoneId", OtherKey="ZoneId", IsForeignKey=true)]
		public Ads_Zone Ads_Zone
		{
			get
			{
				return this._Ads_Zone.Entity;
			}
			set
			{
				Ads_Zone previousValue = this._Ads_Zone.Entity;
				if (((previousValue != value) 
							|| (this._Ads_Zone.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ads_Zone.Entity = null;
						previousValue.Ads.Remove(this);
					}
					this._Ads_Zone.Entity = value;
					if ((value != null))
					{
						value.Ads.Add(this);
						this._ZoneId = value.ZoneId;
					}
					else
					{
						this._ZoneId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ads_Zone");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ads_AdKeywordRelations(Ads_AdKeywordRelation entity)
		{
			this.SendPropertyChanging();
			entity.Ad = this;
		}
		
		private void detach_Ads_AdKeywordRelations(Ads_AdKeywordRelation entity)
		{
			this.SendPropertyChanging();
			entity.Ad = null;
		}
		
		private void Initialize()
		{
			this._Ads_AdKeywordRelations = new EntitySet<Ads_AdKeywordRelation>(new Action<Ads_AdKeywordRelation>(this.attach_Ads_AdKeywordRelations), new Action<Ads_AdKeywordRelation>(this.detach_Ads_AdKeywordRelations));
			this._Ads_Zone = default(EntityRef<Ads_Zone>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads_AdKeywordRelation")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ads_AdKeywordRelation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdId;
		
		private int _KeywordId;
		
		private EntityRef<Ad> _Ad;
		
		private EntityRef<Ads_Keyword> _Ads_Keyword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdIdChanging(int value);
    partial void OnAdIdChanged();
    partial void OnKeywordIdChanging(int value);
    partial void OnKeywordIdChanged();
    #endregion
		
		public Ads_AdKeywordRelation()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					if (this._Ad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdIdChanging(value);
					this.SendPropertyChanging();
					this._AdId = value;
					this.SendPropertyChanged("AdId");
					this.OnAdIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int KeywordId
		{
			get
			{
				return this._KeywordId;
			}
			set
			{
				if ((this._KeywordId != value))
				{
					if (this._Ads_Keyword.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKeywordIdChanging(value);
					this.SendPropertyChanging();
					this._KeywordId = value;
					this.SendPropertyChanged("KeywordId");
					this.OnKeywordIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ad_Ads_AdKeywordRelation", Storage="_Ad", ThisKey="AdId", OtherKey="AdId", IsForeignKey=true)]
		public Ad Ad
		{
			get
			{
				return this._Ad.Entity;
			}
			set
			{
				Ad previousValue = this._Ad.Entity;
				if (((previousValue != value) 
							|| (this._Ad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ad.Entity = null;
						previousValue.Ads_AdKeywordRelations.Remove(this);
					}
					this._Ad.Entity = value;
					if ((value != null))
					{
						value.Ads_AdKeywordRelations.Add(this);
						this._AdId = value.AdId;
					}
					else
					{
						this._AdId = default(int);
					}
					this.SendPropertyChanged("Ad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ads_Keyword_Ads_AdKeywordRelation", Storage="_Ads_Keyword", ThisKey="KeywordId", OtherKey="KeywordId", IsForeignKey=true)]
		public Ads_Keyword Ads_Keyword
		{
			get
			{
				return this._Ads_Keyword.Entity;
			}
			set
			{
				Ads_Keyword previousValue = this._Ads_Keyword.Entity;
				if (((previousValue != value) 
							|| (this._Ads_Keyword.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ads_Keyword.Entity = null;
						previousValue.Ads_AdKeywordRelations.Remove(this);
					}
					this._Ads_Keyword.Entity = value;
					if ((value != null))
					{
						value.Ads_AdKeywordRelations.Add(this);
						this._KeywordId = value.KeywordId;
					}
					else
					{
						this._KeywordId = default(int);
					}
					this.SendPropertyChanged("Ads_Keyword");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._Ad = default(EntityRef<Ad>);
			this._Ads_Keyword = default(EntityRef<Ads_Keyword>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads_Reports")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ads_Report
	{
		
		private System.Nullable<int> _AdId;
		
		private System.Nullable<int> _Clicks;
		
		private System.Nullable<int> _Exposures;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _Hour;
		
		private System.Nullable<int> _DayOfMonth;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		public Ads_Report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<int> AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clicks", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> Clicks
		{
			get
			{
				return this._Clicks;
			}
			set
			{
				if ((this._Clicks != value))
				{
					this._Clicks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exposures", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> Exposures
		{
			get
			{
				return this._Exposures;
			}
			set
			{
				if ((this._Exposures != value))
				{
					this._Exposures = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this._Hour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayOfMonth", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<int> DayOfMonth
		{
			get
			{
				return this._DayOfMonth;
			}
			set
			{
				if ((this._DayOfMonth != value))
				{
					this._DayOfMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdsView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class AdsView
	{
		
		private int _AdId;
		
		private string _Name;
		
		private System.Nullable<int> _AdvertiserId;
		
		private System.Nullable<short> _Status;
		
		private System.Nullable<int> _ZoneId;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<short> _PaymentType;
		
		private System.Nullable<int> _UnitsPurchased;
		
		private System.Nullable<decimal> _CostPerUnit;
		
		private string _Image;
		
		private string _Description;
		
		private string _HtmlCode;
		
		private string _URL;
		
		private System.Nullable<bool> _NewWindow;
		
		private System.Nullable<short> _Weight;
		
		private System.Nullable<int> _MaxImpressionPerHour;
		
		private System.Nullable<int> _MaxImpressionPerDay;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private string _ZoneName;
		
		private int _Impressions;
		
		private int _Clicks;
		
		public AdsView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertiserId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> AdvertiserId
		{
			get
			{
				return this._AdvertiserId;
			}
			set
			{
				if ((this._AdvertiserId != value))
				{
					this._AdvertiserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<short> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> ZoneId
		{
			get
			{
				return this._ZoneId;
			}
			set
			{
				if ((this._ZoneId != value))
				{
					this._ZoneId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<short> PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this._PaymentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsPurchased", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> UnitsPurchased
		{
			get
			{
				return this._UnitsPurchased;
			}
			set
			{
				if ((this._UnitsPurchased != value))
				{
					this._UnitsPurchased = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostPerUnit", DbType="Money")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<decimal> CostPerUnit
		{
			get
			{
				return this._CostPerUnit;
			}
			set
			{
				if ((this._CostPerUnit != value))
				{
					this._CostPerUnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HtmlCode", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string HtmlCode
		{
			get
			{
				return this._HtmlCode;
			}
			set
			{
				if ((this._HtmlCode != value))
				{
					this._HtmlCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(512)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewWindow", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<bool> NewWindow
		{
			get
			{
				return this._NewWindow;
			}
			set
			{
				if ((this._NewWindow != value))
				{
					this._NewWindow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<short> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxImpressionPerHour", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> MaxImpressionPerHour
		{
			get
			{
				return this._MaxImpressionPerHour;
			}
			set
			{
				if ((this._MaxImpressionPerHour != value))
				{
					this._MaxImpressionPerHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxImpressionPerDay", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<int> MaxImpressionPerDay
		{
			get
			{
				return this._MaxImpressionPerDay;
			}
			set
			{
				if ((this._MaxImpressionPerDay != value))
				{
					this._MaxImpressionPerDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this._DateModified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneName", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string ZoneName
		{
			get
			{
				return this._ZoneName;
			}
			set
			{
				if ((this._ZoneName != value))
				{
					this._ZoneName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impressions", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public int Impressions
		{
			get
			{
				return this._Impressions;
			}
			set
			{
				if ((this._Impressions != value))
				{
					this._Impressions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clicks", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public int Clicks
		{
			get
			{
				return this._Clicks;
			}
			set
			{
				if ((this._Clicks != value))
				{
					this._Clicks = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads_ReportsView")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ads_ReportsView
	{
		
		private System.Nullable<int> _Impressions;
		
		private System.Nullable<int> _Clicks;
		
		private System.Nullable<int> _AdId;
		
		public Ads_ReportsView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impressions", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<int> Impressions
		{
			get
			{
				return this._Impressions;
			}
			set
			{
				if ((this._Impressions != value))
				{
					this._Impressions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clicks", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> Clicks
		{
			get
			{
				return this._Clicks;
			}
			set
			{
				if ((this._Clicks != value))
				{
					this._Clicks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<int> AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads_Keywords")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ads_Keyword : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KeywordId;
		
		private string _Keyword;
		
		private EntitySet<Ads_AdKeywordRelation> _Ads_AdKeywordRelations;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKeywordIdChanging(int value);
    partial void OnKeywordIdChanged();
    partial void OnKeywordChanging(string value);
    partial void OnKeywordChanged();
    #endregion
		
		public Ads_Keyword()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int KeywordId
		{
			get
			{
				return this._KeywordId;
			}
			set
			{
				if ((this._KeywordId != value))
				{
					this.OnKeywordIdChanging(value);
					this.SendPropertyChanging();
					this._KeywordId = value;
					this.SendPropertyChanged("KeywordId");
					this.OnKeywordIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this.OnKeywordChanging(value);
					this.SendPropertyChanging();
					this._Keyword = value;
					this.SendPropertyChanged("Keyword");
					this.OnKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ads_Keyword_Ads_AdKeywordRelation", Storage="_Ads_AdKeywordRelations", ThisKey="KeywordId", OtherKey="KeywordId")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<Ads_AdKeywordRelation> Ads_AdKeywordRelations
		{
			get
			{
				if ((this.serializing 
							&& (this._Ads_AdKeywordRelations.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Ads_AdKeywordRelations;
			}
			set
			{
				this._Ads_AdKeywordRelations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ads_AdKeywordRelations(Ads_AdKeywordRelation entity)
		{
			this.SendPropertyChanging();
			entity.Ads_Keyword = this;
		}
		
		private void detach_Ads_AdKeywordRelations(Ads_AdKeywordRelation entity)
		{
			this.SendPropertyChanging();
			entity.Ads_Keyword = null;
		}
		
		private void Initialize()
		{
			this._Ads_AdKeywordRelations = new EntitySet<Ads_AdKeywordRelation>(new Action<Ads_AdKeywordRelation>(this.attach_Ads_AdKeywordRelations), new Action<Ads_AdKeywordRelation>(this.detach_Ads_AdKeywordRelations));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ads_Zones")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Ads_Zone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZoneId;
		
		private string _Name;
		
		private string _Alias;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<short> _Width;
		
		private System.Nullable<short> _Height;
		
		private string _Description;
		
		private string _Size;
		
		private EntitySet<Ad> _Ads;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZoneIdChanging(int value);
    partial void OnZoneIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnWidthChanging(System.Nullable<short> value);
    partial void OnWidthChanged();
    partial void OnHeightChanging(System.Nullable<short> value);
    partial void OnHeightChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    #endregion
		
		public Ads_Zone()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ZoneId
		{
			get
			{
				return this._ZoneId;
			}
			set
			{
				if ((this._ZoneId != value))
				{
					this.OnZoneIdChanging(value);
					this.SendPropertyChanging();
					this._ZoneId = value;
					this.SendPropertyChanged("ZoneId");
					this.OnZoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="VarChar(150)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<short> Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<short> Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", AutoSync=AutoSync.Always, DbType="VarChar(63)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ads_Zone_Ad", Storage="_Ads", ThisKey="ZoneId", OtherKey="ZoneId")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9, EmitDefaultValue=false)]
		public EntitySet<Ad> Ads
		{
			get
			{
				if ((this.serializing 
							&& (this._Ads.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Ads;
			}
			set
			{
				this._Ads.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ads(Ad entity)
		{
			this.SendPropertyChanging();
			entity.Ads_Zone = this;
		}
		
		private void detach_Ads(Ad entity)
		{
			this.SendPropertyChanging();
			entity.Ads_Zone = null;
		}
		
		private void Initialize()
		{
			this._Ads = new EntitySet<Ad>(new Action<Ad>(this.attach_Ads), new Action<Ad>(this.detach_Ads));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
}
#pragma warning restore 1591
