<?xml version="1.0" encoding="utf-8"?><Database Name="saga" Class="NotificationDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dssrv.interedlb.sabis.net,1433;Initial Catalog=saga;User ID=sa" SettingsObjectName="lw.NotificationSystem.Properties.Settings" SettingsPropertyName="NotificationSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Notification_Row" Member="Notification_Rows">
    <Type Name="Notification_Row">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SenderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ReceiverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiverName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ReadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>