<?xml version="1.0" encoding="utf-8"?><Database Name="saga" Class="GroupsDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DSGN10\SQL2005;Initial Catalog=saga;Persist Security Info=True;User ID=sa" SettingsObjectName="lw.Groups.Properties.Settings" SettingsPropertyName="sagaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UniqueName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Region" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="University" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Privacy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MembershipApproval" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Mission" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Security" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LegalStatus" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupsMembers" Member="GroupsMembers">
    <Type Name="GroupsMember">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>